SeisComP3/seiscomp3

src/seedlink/plugins/scream2_plugin/config.h, src/seedlink/plugins/scream2_plugin/descriptions/seedlink_scream_ring.xml, src/seedlink/plugins/scream2_plugin/dispatch_ring.c, src/seedlink/plugins/scream2_plugin/gcf.c, src/seedlink/plugins/scream2_plugin/gputil.c, src/seedlink/plugins/scream2_plugin/main.c, src/seedlink/plugins/scream2_plugin/scream.c, src/seedlink/plugins/scream2_plugin/scream.h, src/seedlink/plugins/scream2_plugin/util.h, src/seedlink/templates/scream_ring/seedlink_plugin.tpl, src/seedlink/templates/scream_ring/setup.py
Tested by Sheila Peacock (Blacknest, UK) and did not get negative feedback since October, 2014.
=> Added TCP support to scream ring plugin

src/ipgp/plugins/locator/hypo71/hypo71.cpp
In the depth search algorithm, the best solution is either the one with abslute lowest RMS, or the one with equally lowest RMS and lowest horizontal errors
Jean-Marie.
=> Corrected decision matrix for depth search phase

src/trunk/apps/fdsnws/fdsnws/station.py
Depending on the request level the fdsnws-station output in text mode is sorted by
* level=net: ```net networkStartTime```
* level=sta: ```net.sta stationStartTime```
* level=cha: ```net.sta.loc.cha channelStartTime```
=> [fdsnws] sort text output of station service, #33

src/gui-qt4/apps/scrttv/descriptions/scrttv.xml
Just spent 15 minutes to find how the code should be specified ;)
=> Added example for streams.code option

src/seedlink/plugins/descriptions/seedlink_mseedfifo.xml, src/seedlink/plugins/mseedfifo_plugin/mseedfifo_plugin.c, src/seedlink/templates/mseedfifo/seedlink_plugin.tpl, src/seedlink/templates/mseedfifo/setup.py, src/utils/apps/msrtsimul.py
msrtsimul now waits until the timestamp of the last data point in the record has been reached instead of the first.
=> waits until the time of the last data point in record has been reached

src/gui-qt4/apps/scmv/eventdata.cpp, src/gui-qt4/apps/scmv/eventdata.h, src/gui-qt4/apps/scmv/mvmainwindow.cpp, src/gui-qt4/apps/scmv/mvmainwindow.h
@ovsm-dev please test and comment. You are also invited to improve the current solution. This commit allows to plot focal mechanisms on top of the origin symbols colored with depths and sized with the magnitude.
=> [scmv] Add plotting of focal mechanisms / moment tensors

src/sed/apps/scvsmag/config/sc3ml_0.7__quakeml_1.2-RT_eewd.xsl, src/sed/apps/scvsmag/config/sc3ml_0.7__shakealert.xsl, src/sed/apps/scvsmag/descriptions/scvsmag.rst, src/sed/apps/scvsmag/scvsmag.cpp, src/sed/apps/scvsmag/scvsmag.h, src/sed/apps/scvsmag/scvsmaglog.py
* New MVS magnitudes are now created at every update to preserve the history of the alerting/detection in the database. 
* Single station magnitude estimates have been added to MVS facilitating the analysis of station contributions
* Updates and bug fixes to the xslts
=> MVS magnitude

src/gns/plugins/magnitudes/MLR/descriptions/global_mlr.rst, src/gns/plugins/magnitudes/MLR/descriptions/global_mlr.xml
Corrections and additional reference to the MLr GNS/Geonet  local magnitude plugin.
(Latex style used for the magnitude formula )
=> Mlr documentation correction and complement

src/trunk/apps/python/scevtlog.py
This was pointed out to me by @crlebalnc.
It's purely window dressing. But consistency is a good thing, right?
=> Small change to scevtlog.py for consistency.

src/seedlink/plugins/serial_plugin/CMakeLists.txt, src/seedlink/plugins/serial_plugin/serial_config.h.in, src/seedlink/plugins/serial_plugin/serial_plugin.cc, src/trunk/libs/seiscomp3/datamodel/diff.cpp, src/trunk/libs/seiscomp3/datamodel/utils.cpp
Here's a small set of changes I needed to make to allow compilation on alpine linux.
compile options used ...
CMAKE_C_FLAGS="-D__off64_t=off64_t"
CMAKE_CXX_FLAGS="-std=c++0x"
```
/pkg/src/seiscomp3-release-jakarta-2016.062/src/seedlink/plugins/serial_plugin/serial_plugin.cc: In function 'int SeedlinkPlugin_private::open_dev(mode_t)':
/pkg/src/seiscomp3-release-jakarta-2016.062/src/seedlink/plugins/serial_plugin/serial_plugin.cc:274:19: error: call of overloaded 'cfmakeraw(termios*)' is ambiguous
cfmakeraw(&tio);
^
/pkg/src/seiscomp3-release-jakarta-2016.062/src/seedlink/plugins/serial_plugin/serial_plugin.cc:226:5: note: candidate: int SeedlinkPlugin_private::cfmakeraw(termios*)
int cfmakeraw(struct termios *termios_p)
^
In file included from …
```
=> compile on alpine linux

src/ipgp/apps/ew2sc3/ew2sc3.cpp
Corrected typo preventing the import of S-phases from EarthWorm
S-phases were ignored
=> Bug correction for S-phases in ew2sc3

src/trunk/apps/fdsnws/CMakeLists.txt, src/trunk/apps/fdsnws/descriptions/fdsnws.rst, src/trunk/apps/fdsnws/descriptions/fdsnws.xml, src/trunk/apps/fdsnws/fdsnws.py, src/trunk/apps/fdsnws/fdsnws/dataselect.py, src/trunk/apps/fdsnws/fdsnws/gnupg.py, src/trunk/apps/fdsnws/fdsnws/http.py, src/trunk/apps/fdsnws/fdsnws/reqtrack.py, src/trunk/apps/fdsnws/fdsnws/station.py, src/trunk/apps/fdsnws/fdsnws_fetch.py, src/trunk/apps/fdsnws/share/dataselect.wadl
* request statistics (reqtrack)
* access to restricted data (auth extension)
* fdsnws_fetch utility
=> EIDA fdsnws developments

src/trunk/apps/fdsnws/fdsnws.py
I noticed fdsnws was not filtering my stations.. I think you guys swapped some variables.
Best,
Mathijs
=> Fixed bug in fdsnws.py where dataselect/station filter are swapped

src/trunk/apps/fdsnws/share/dataselect.wadl, src/trunk/apps/fdsnws/share/event-builder.html, src/trunk/apps/fdsnws/share/event.wadl, src/trunk/apps/fdsnws/share/station-builder.html, src/trunk/apps/fdsnws/share/station.wadl
=> [fdsnws] Fix errors in application.wadl and URL builders

src/trunk/libs/seiscomp3/datamodel/exchange/CMakeLists.txt, src/trunk/libs/seiscomp3/datamodel/exchange/ims10.cpp, src/trunk/libs/seiscomp3/datamodel/exchange/ims10.h
Adds IMS1.0 short bulletin output support to exchange library
Initial commit
=> IMS1.0 output format

src/trunk/apps/python/scart.py
Current scart implementation prevent dumping a large amount of stations and channels because the time spent in sorting the records is way, way larger than the IO time needed to read/write the data.
This patch fix this behaviour so that scart is no longer a bottleneck. The patch make use of bisect module to keep the list of stream/records constantly sorted.
Here is the scart profiler output when trying to dump 20 minutes of data from ~700 stations (3 channels each):
```
python -m cProfile -o prof /usr/local/bin/scart -dsE -t '2016/07/20 03:24:00~2016/07/20 03:44:00' -n '8X,BW,CH,CR,CZ,FR,G,GE,GR,GU,HS,HU,IU,IV,MN,NI,OE,OX,PL,RA,RD,RF,RO,SI,SK,SL,ST,SX,TH,XG,Z3' -c '(B|H)H(Z|N|E)' --files 2500  /alparray/ > sorted.mseed
>>> import pstats
>>> p = pstats.Stats('prof')
>>> …
```
=> Improved scart performance

CHANGELOG.md, src/ipgp/apps/3rd-party/Hypo71PC/README, src/ipgp/apps/3rd-party/Hypo71PC/hypo1m2.f, src/ipgp/apps/3rd-party/Hypo71PC/hypo2.f, src/ipgp/apps/3rd-party/Hypo71PC/input1.f, src/ipgp/apps/3rd-party/Hypo71PC/main.f, src/ipgp/apps/3rd-party/Hypo71PC/single.f, src/ipgp/plugins/locator/hypo71/hypo71.cpp
Hypo71PC fix from Matthieu Sylvander when longitude(closest_station) * longitude(earthquake) < 0 which happends around Greenwitch meridian and line of date change.
Hypo71 locator plugin fix when all arrival uncertainties were not set. This led to a division by 0 and some erroneous int to string cast.
=> Hypo71 fixes

src/trunk/apps/processing/scamp/amptool.cpp, src/trunk/apps/processing/scamp/amptool.h
This should fix the issue reported in #152.
=> [scamp] Handle pick and amplitude removals

src/sed/apps/scvsmag/timeline.cpp
Adds compatibility with envelopeChannel names being produced by sceewenv.
=> Compatibility with sceewenv

src/trunk/apps/python/scart.py
This is just a simple suggestion.
=> [scart] Add strong motion channels N and G to default channel filter

src/sed/apps/scvsmag/config/sc3ml_0.7__quakeml_1.2-RT_eewd.xsl
This commit fix the code but file naming consistency remains an issue (issue #187).
=> [scvsmaglog] Update database version number.

src/trunk/libs/seiscomp3/io/recordstream/descriptions/global_recordstream.rst, src/trunk/libs/seiscomp3/io/recordstream/sdsarchive.cpp, src/trunk/libs/seiscomp3/io/recordstream/sdsarchive.h
Please consider the following implementation of the sdsarchive with support of multiple SDS structures.
=> Implemented a multi SDS support on sdsarchive RecordStream.

doc/build-doc.py, src/arclink/apps/arclinkfetch/arclink_fetch.py, src/arclink/apps/arclinktool/arclinktool.py, src/arclink/apps/misc/sync_db.py, src/arclink/apps/webinterface/webinterface.py, src/arclink/apps/webreqlog/webreqlog.py, src/arclink/libs/python/seiscomp/arclink/client.py, src/arclink/libs/python/seiscomp/arclink/handler.py, src/arclink/libs/python/seiscomp/db/seiscomp3/inventory.py, src/arclink/libs/python/seiscomp/db/seiscomp3/routing.py, src/arclink/libs/python/seiscomp/db/xmlio/inventory.py, src/arclink/libs/python/seiscomp/db/xmlio/qc.py, src/arclink/libs/python/seiscomp/db/xmlio/routing.py, src/arclink/libs/python/seiscomp/db/xmlio/xmlwrap.py, src/arclink/libs/python/seiscomp/sds.py, src/arclink/libs/python/session/__init__.py, src/nettab/libs/python/nettab/helpers.py, src/nettab/libs/python/nettab/nettab.py, src/trunk/apps/fdsnws/fdsnws.py, src/trunk/apps/python/scalert.py, src/trunk/apps/python/scvoice.py, src/utils/libs/python/seiscomp/fseed.py, src/utils/libs/python/seiscomp/iniparser.py, src/utils/libs/python/seiscomp/xmlparser.py
This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
=> Compare to `None` using identity `is` operator

src/trunk/apps/fdsnws/fdsnws/dataselect.py
Dataselect normally uses 2 HTTP status codes -- 200 (data available) and 204/404 (no data available). Unauthorized data is simply filtered out, which can be confusing -- a user getting 204/404 does not know if data is not available at all or he is not authorized to get restricted data. In the latter case he should contact the data center.
This pull request replaces 204/404 by 403 (forbidden) if access to all requested data was denied. If the request includes non-restricted channels, still 204/404 is used for compatibility reasons. We decided to not add an additional non-standard query parameter like "noaccess=403", which would make client logic more complex (some servers give bad request error if unsupported query parameters are used).
Note that 403 is listed as "Authentication failed or …
=> [fdsnws] use response code 403 if access to all requested data was denied

CHANGELOG.md, src/ipgp/apps/3rd-party/Hypo71PC/H_param.f, src/ipgp/plugins/locator/hypo71/hypo71.cpp, src/ipgp/plugins/locator/hypo71/hypo71.h
This PR includes two changes:
* Increase maximum phase number to 1001
* Raise an error if a profile does not include a velocity model
* Fix bug which re-uses the velocity model if a profile has changed to one which does not include a velocity model
=> Hypo71 max phases set to 1001

src/trunk/libs/seiscomp3/io/recordstream/sdsarchive.cpp
This PR fixes the issue discussed [here](https://forum.seiscomp3.org/t/fdsnws-missing-data/1260).
The `start_time` of the miniseed files wasn't handled properly in the [isEnd](https://github.com/SeisComP3/seiscomp3/blob/master/src/trunk/libs/seiscomp3/io/recordstream/sdsarchive.cpp#L410) method. These changes improve things but do not take into account microseconds, only 1e-4 seconds. The last decimals are stored in the blockette 1001 (see SEED manual, p. 124). The miniseed library [uses this blockette 1001](https://github.com/SeisComP3/seiscomp3/blob/master/src/system/libs/3rd-party/libmseed/msrutils.c#L543) but this blockette isn't currently available in the `isEnd` method. Do you think 1e-4 seconds is good enough or do we have to also parse the blockette 1001?
=> Fix FDSNWS missing data

src/trunk/apps/fdsnws/fdsnws/request.py
This pull request supports date request on Unix epoch, see #225.
=> [fdsnws] Support epoch dates

src/trunk/apps/fdsnws/descriptions/fdsnws.xml, src/trunk/apps/fdsnws/fdsnws.py, src/trunk/apps/fdsnws/fdsnws/http.py, src/trunk/apps/fdsnws/fdsnws/station.py, src/trunk/apps/fdsnws/share/station.html, src/trunk/apps/fdsnws/share/station.wadl
- expose parameter only if data availability information is enabled via config
- disable data availability information by default
=> [fdsnws] matchtimeseries WADL parameter

src/trunk/apps/fdsnws/descriptions/fdsnws.rst, src/trunk/apps/fdsnws/descriptions/fdsnws.xml, src/trunk/apps/fdsnws/fdsnws.py, src/trunk/apps/fdsnws/fdsnws/dataselect.py, src/trunk/apps/fdsnws/fdsnws/reqlog.py
Implement file-based (JSON) request log that is easier handle than "reqtrack" database and may help with GDPR compliance.
=> [fdsnws] implement request log for dataselect

src/sed/apps/scvsmag/descriptions/scvsmag.rst
Allowing a functional default VS setup.
=> [VS/doc] Update scvsmag.rst

src/ipgp/apps/ew2sc3/ew2sc3.cpp
EarthWorm implementaion of NLLoc doesn't handle correctly full SCNL and location code information is often lost in the location process in EarthWorm.
This pull request correct and secure the pick location code search algorithm to retrieve full SCNL before pushing the picks to SeisComP3.
=> ew2sc3 loccode search algorithm correction
