src/nettab/apps/tabinvmodifier/tabinvmodifier.py

tabinvmodifier run() method was returning 0 instead of True rendering it unusable in newer environments (tested with swig 3.0.2-1 - debian/testing). This should correct this bug.

Bug in tabinvmodifier

---

src/ipgp/apps/ew2sc3/ew2sc3.cpp

When the filter criteria for module_ID and/or institute_ID is set to WILDCARD in the config file, we want all messages to be accepted, whatever their module_ID and/or institude_ID is.
This was not the case in the previous test and have been corrected.
Jean-Marie Saurel

Corrected filtering of MOD_ID and INST_ID

---

src/ipgp/plugins/locator/hypo71/hypo71.cpp

The hypo71 locator plugin crashes when built with enabled compiler optimizations. I fixed the crash as well as some uninitialized values. @ovsm-dev, can you please check if the initializations are correct? I added comments to the commit.

[hypo71] Fixed crash when build as Release

---

src/trunk/apps/fdsnws/fdsnws/event.py
src/trunk/apps/fdsnws/fdsnws/station.py

This fix resolves a bug in the station and event service when data is requested in text format, e.g.
http://geofon.gfz-potsdam.de/fdsnws/station/1/query?level=channel&format=text&network=*

[fdsnws] fixed missing lines in text format of station and event service

---

src/trunk/apps/processing/scevent/eventtool.cpp
src/trunk/apps/processing/scevent/eventtool.h
src/trunk/apps/processing/scevent/util.cpp

To be able to run full offline processing through pipes, scevent needs the ```--ep``` functionality as well which is the objective of this PR.
Example:
```
scevent --ep origins_and_picks.xml > events.xml
```
scevent will read all origin from the XML file and either try to associate them with existing events or create new events. The data model is being updated and written to stdout in XML format again.

[scevent] Added --ep to process offline datasets

---

src/trunk/apps/fdsnws/share/event.wadl

- this is the correct parameter name according to fdsn ws specification (http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf, page 5)
- this is also the parameter at it is actually implemented.

change: param name="includemagnitudes" >> "includeallmagnitudes"

---

src/gui-qt4/libs/seiscomp3/gui/core/CMakeLists.txt
src/gui-qt4/libs/seiscomp3/gui/core/lut.h
src/gui-qt4/libs/seiscomp3/gui/core/recordwidget.cpp
src/gui-qt4/libs/seiscomp3/gui/core/spectrogramrenderer.cpp
src/gui-qt4/libs/seiscomp3/gui/core/spectrogramrenderer.h
src/gui-qt4/libs/seiscomp3/gui/core/spectrogramwidget.cpp
src/gui-qt4/libs/seiscomp3/gui/core/spectrogramwidget.h
src/gui-qt4/libs/seiscomp3/gui/datamodel/pickerview.cpp
src/gui-qt4/libs/seiscomp3/gui/datamodel/pickerview.h
src/gui-qt4/libs/seiscomp3/gui/datamodel/pickerview.ui
src/trunk/libs/seiscomp3/core/version.h
src/trunk/libs/seiscomp3/io/recordfilter/CMakeLists.txt
src/trunk/libs/seiscomp3/io/recordfilter/spectralizer.cpp
src/trunk/libs/seiscomp3/io/recordfilter/spectralizer.h

This implements a spectrogram layer in the manual picker window. The spectrogram view can be toggled with ctrl+s and is by default off. A new toolbar has been added as well to configure the spectrogram, in particular spectra window length and window overlap.
Ping @marcopovitch.

[scolv] Initial spectrogram implementation

---

src/trunk/apps/tools/scconfig/CMakeLists.txt

Setting SC_GLOBAL_GUI to OFF is not enough to get ride of Qt4 as scconfig is still compiled.
This patch disable scconfig compilation when SC_GLOBAL_GUI is set to OFF so libqt4 is not required anymore.
The main purpose is to be able to compile a SeisComP headless version with less dependencies. It could be useful for people as us who work to dockerize SeisComP or people who aim to run it on small platform (like Raspberry Pi).

[scconfig] Don't compile it if SC_GLOBAL_GUI=OFF

---

src/ipgp/plugins/locator/hypo71/hypo71.cpp

For station elevation below -999 meters, TEST(20) should be set to a value higher than 1, and station elevation in the HYPO71.INP file should be set to station_elevation / TEST(20).
For an OBS at -4523m (4523m below sea level), TEST(20) should be set at 10 and station elevation in the station list of HYPO71.INP should be set to -452. And all stations elevations in the HYPO71.INP file should be divided by 10.
TODO : make this intelligent by removing TEST(20) from the profile file, and setting it to 10 if one of the stations elevation is lower than -999.

Bug for stations with elevation <-999 corrected

---

src/ipgp/plugins/magnitudes/md/md.cpp

Md plugin didn't take into account changes applied to snrMin in the waveform review window.
When snrMin is set to Disabled, md plugin doesn't try to find the end of the coda, but takes the manual pick as the end of the coda.
When snrMin is set to a value, md plugin searches for the end of the coda starting from the manual pick, until the ratio between signal and pre-event noise is lower than snrMin.

Fixed md plugin use of snrMin when changed in the waveform review window

---

src/trunk/apps/python/scalert.py

Fix missing seiscomp3.System import, that prevents scalert.py to  start properly.

add missing seiscomp3.System import

---

src/trunk/apps/tools/inventory/fdsnxml2inv/convert2sc3.cpp
src/trunk/libs/seiscomp3/core/timewindow.h

- Previously, adjacent epochs where the end time
of the first and start time of the second are
identical were considered overlapping and skipped
in fdsnxml2inv.
- The change to TimeWindow::contains is not required
for the fix, but I have not looked where or how it is
used and it may be required for consistency. Nor have
I checked whether other changes are required.

Allow adjacent epochs with 'touching' start/end times.

---

src/trunk/apps/fdsnws/fdsnws/dataselect.py

Hi devs, for our default fdsnws-dataselect exporting name we will add the current request time. If you are interested you can merge this pull request. It interpolates `%time` in `fdsnws.cfg:fileNamePrefix` to the current time in ISO-format.
`fileNamePrefix = fdsnws-%time` results in `fdsnws-2017-01-16T16_38_39.mseed`.

Added %time interpolation for dataselect filename

---

src/sed/apps/scvsmag/scvsmag.cpp

Before this, preferred origins that have no arrival would crash scvsmag when using OriginQuality.azimuthalGap.
Now, if it has no arrival, scvsmag exits without doing Mvs, but VS's expirationTime is updated (using the current preferred origin).
This was [issue 92](https://github.com/SeisComP3/seiscomp3/issues/92), this is the second try I closed the first.

Fixes a bug in scvsmag with preferred origins without arrivals (second try).

---

src/ipgp/plugins/locator/hypo71/descriptions/global_hypo71.xml
src/ipgp/plugins/locator/hypo71/hypo71.cpp

@ovsm-dev, this patch allows to use path variables in hypo71 settings, e.g. ```@DATADIR@``` and some defaults have been adopted to common user settings. @gempa-dirk can further comment on it.

[hypo71] Allow parameter configuration using variables

---

src/gui-qt4/apps/scshowevent/CMakeLists.txt
src/gui-qt4/apps/scshowevent/main.cpp
src/gui-qt4/apps/scshowevent/sendevent.cpp
src/gui-qt4/apps/scshowevent/sendevent.h

Small commandline utility to send notification to scolv to show event details.
Usage: scsendevent -E  \<eventID\>
Variable <commands.target> should be set to appropriate value. You can use
regular expressions to specify a group of clients (HINT: all = '.*$').

[scshowevent] commandline utility to send notifications to scolv to show event details 

---

src/ipgp/plugins/magnitudes/md/descriptions/global_md.xml
src/ipgp/plugins/magnitudes/md/md.cpp

Hi @gempa-jabe  and @jmsaurel, 
For small earthquake the default values used for TAPER, SIGNAL_LENGTH  and SNR_MIN  have to be set to some optimized value. This patch fix this.
The filter parameter for Butterworth Band Pass (Case 6, 7, 8 md.butterworth) is not parsed, but hardcoded value is set instead (3, 1, 15).  Perhaps a better way is to use the sc3 filter grammar (BW_LP, BW_HP, BW) rather than too many cases.
Regards
Marc

[Md] Allow to set TAPER, SIGNAL_LENGTH  and SNR_MIN values

---

src/trunk/apps/processing/scamp/amptool.cpp

The `scamp` reprocessing doesn't work with PostgreSQL (see logs). Replacing 
```
dbQuery += " group by Amplitude." + _T("pickID");
```
by
```
dbQuery += " group by PPick." + _T("publicID") + ", Pick._oid";
```
is working for me. I try with PostgreSQL but not with MySQL so it may crash with MySQL.
Logs:
```
$ seiscomp exec scamp --debug --start-time '2016-03-06 00:00:00' --end-time '2016-03-08 00:00:00' --commit
15:24:50 [debug] Adding plugin path: .
15:24:50 [debug] Adding plugin path: /home/seiscomp/.seiscomp3/plugins
15:24:50 [debug] Adding plugin path: /home/seiscomp/Applications/seiscomp3/lib/plugins
15:24:50 [debug] Adding plugin path: /home/seiscomp/Applications/seiscomp3/lib
15:24:50 [debug] Adding plugin path: /home/seiscomp/Applications/seiscomp3/share/plugins
15:24:50 [debug] …
```

Fix scamp reprocessing

---

src/sed/apps/scvsmag/scvsmag.cpp

Before all MVS children objects would have a precision of 1.0s in
creation times. This is wrong since the corresponding origin sometimes
appears to be created after its magnitude, e.g.:
<origin publicID="Origin#20161103054840.154469.2647">                        ...
<creationInfo>                                                             ...
<creationTime>2016-11-03T05:48:40.154452Z</creationTime>
</creationInfo>                                                            ...
<stationMagnitude publicID="StationMagnitude#20161103054841.032559.49535"> ...
<creationInfo>                                                           ...
<creationTime>2016-11-03T05:48:40.0000Z</creationTime>
<version>10</version>
</creationInfo>
</stationMagnitude> …

Fixes the lack of precision in MVS creationTime.

---

src/sed/apps/scvsmag/scvsmag.cpp

The VS code calculates both individual station magnitudes and a global magnitude, the latest being inferred together with the likelihood in a loop here:
https://github.com/SeisComP3/seiscomp3/blob/02f18cf1479a13eca385f6ec42681f335b5d8f97/src/sed/apps/scvsmag/scvsmag.cpp#L925
This loop goes from M0.5 to M9.0 and is supposed to pick the global VS magnitude at the likelihood peak. To do so a conditional record of the last trial magnitude breaks when the likelihood starts to decrease and the magnitude at highest likelihood is recorded. Note this loop make use of a sum of likelihood over all available individual station magnitude in a nested loop.
During large earthquakes, some stations (the clipped ones?) have PG*=-1 and stationmagnitude=nan. These can't be processed in scvsmag and result in …

Fix scvsmag when processing NaN stationmagnitude

---

src/ipgp/apps/3rd-party/Hypo71PC/hypo1m2.f
src/ipgp/apps/3rd-party/Hypo71PC/input1.f
src/ipgp/apps/3rd-party/Hypo71PC/single.f

Longitude 0/180 bug correction forgot the case when a fixed starting point of the iteration was passed (option USE_TRIAL_POSITION set to true in the profile)

[Hypo71PC] bug when starting point fixed

---

src/sed/apps/scvsmag/scvsmag.cpp

Without this fix, scvsmag trash when an origin has no quality.azimuthalGap. I can happen: scanloc preliminary origins don't have quality.azimuthalGap.

Fix scvsmag.cpp

---

src/trunk/libs/xml/0.10/sc3ml_0.10__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.10/sc3ml_0.10__quakeml_1.2.xsl
src/trunk/libs/xml/0.5/sc3ml_0.5__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.5/sc3ml_0.5__quakeml_1.2.xsl
src/trunk/libs/xml/0.6/sc3ml_0.6__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.6/sc3ml_0.6__quakeml_1.2.xsl
src/trunk/libs/xml/0.7/sc3ml_0.7__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.7/sc3ml_0.7__quakeml_1.2.xsl
src/trunk/libs/xml/0.8/sc3ml_0.8__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.8/sc3ml_0.8__quakeml_1.2.xsl
src/trunk/libs/xml/0.9/sc3ml_0.9__quakeml_1.2-RT.xsl
src/trunk/libs/xml/0.9/sc3ml_0.9__quakeml_1.2.xsl

I was looking to update the SC3ML ObsPy module with the 0.10 version but the XSLT files doesn't generate valid QuakeML files. The following new fields aren't in the QuakeML:
- Comment/start
- Comment/end
- TimeQuantity/pdf
- RealQuantity/pdf
I don't think they have a corresponding node in the QuakeML so I removed them. I also add a small fix for the arrival weight mapping.
I mainly tested the conversion to the QuakeML format. QuakeML-RT seems good but I didn't test a lot. Let me know if I did something wrong!

Fix XSLT files for SC3ML 0.10

---

src/trunk/apps/processing/scevent/eventtool.cpp
src/trunk/apps/processing/scevent/eventtool.h

This is useful to allow external applications writing external origins to the database and associating as additional origin to the seiscomp3 solution of the same event, to properly work in scolv.
Due to the  events caching a new origin in the database is not seen by scevent and this prevent few operations to be properbly completed in scolv:
- setting an external origin as preferred
- moving an external origin to another event

[scevent]: allow scevent to clear its cache via messaging system

---

src/trunk/apps/fdsnws/fdsnws/event.py
src/trunk/apps/fdsnws/fdsnws/http.py

This pull request is a response to #183 
A 204 response code requires an empty body. That's why a None was return in [fdsnws/http.py](https://github.com/SeisComP3/seiscomp3/blob/8a2dc6022429fe024e3b6c1f0ecacba2a02cc6af/src/trunk/apps/fdsnws/fdsnws/http.py#L61).
Twisted, however, turns a None response into a 500. I changed the None to an empty string.
In addition, and unrelated, I decided to no longer log 204 responses which have been converted to 404 via the request parameter `nodata=404` as a warning message.
Next I turn the 204 in response to a catalog filter parameter into a 400 since the service documentation as well as the WADL forbids this parameter.

Fix no data 500

---

CHANGELOG.md
src/trunk/apps/processing/scautoloc/app.cpp
src/trunk/apps/processing/scautoloc/config.cpp

This option was always "false", regardless of what was specified in config files. The only way to get autoloc.useManualPicks set to "true" was by calling scautoloc on command line with option '--use-manual-picks'.
I think this PR should fix the bug, I can't check myself locally though, since I don't have time to set up compilation right now.

[scautoloc] Bugfix: correctly read config option autoloc.useManualPicks

---

src/trunk/apps/fdsnws/fdsnws/http.py

It happened multiple times that gpg couldn't spawn a process due to a lack of memory on our system. The user sees this as `400` `Bad Request` while it is technically a server error. I added a catch for `OSError` that returns `500`.
Please review.

Catch OSError on pgp.decryt

---

src/trunk/libs/xml/0.10/sc3ml_0.10__quakeml_1.2.xsl
src/trunk/libs/xml/0.11/sc3ml_0.11__quakeml_1.2.xsl
src/trunk/libs/xml/0.5/sc3ml_0.5__quakeml_1.2.xsl
src/trunk/libs/xml/0.6/sc3ml_0.6__quakeml_1.2.xsl
src/trunk/libs/xml/0.7/sc3ml_0.7__quakeml_1.2.xsl
src/trunk/libs/xml/0.8/sc3ml_0.8__quakeml_1.2.xsl
src/trunk/libs/xml/0.9/sc3ml_0.9__quakeml_1.2.xsl

If a pick wasn't referenced in an arrival but only in an amplitude, it wasn't retained in the XSLT conversion to QuakeML. Apparently, [this can happen](https://github.com/obspy/obspy/issues/2273).
This PR fixes that. All picks referenced by arrivals or amplitudes are kept. With the sample file provided in the ObsPy issue, I now have 7 picks as expected.

Copy picks referenced by amplitudes

---

src/trunk/libs/xml/0.10/sc3ml_0.10__quakeml_1.2.xsl
src/trunk/libs/xml/0.11/sc3ml_0.11__quakeml_1.2.xsl
src/trunk/libs/xml/0.5/sc3ml_0.5__quakeml_1.2.xsl
src/trunk/libs/xml/0.6/sc3ml_0.6__quakeml_1.2.xsl
src/trunk/libs/xml/0.7/sc3ml_0.7__quakeml_1.2.xsl
src/trunk/libs/xml/0.8/sc3ml_0.8__quakeml_1.2.xsl
src/trunk/libs/xml/0.9/sc3ml_0.9__quakeml_1.2.xsl

In the QuakeML format, there is the possibility to create custom nodes. This PR modify the XSLT stylesheets to put the seiscomp nodes that are not mapped in QuakeML in these custom fields. This allows some round-trip conversion without loss of data. For instance, the `pdf` node doesn't exist in QuakeML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<seiscomp xmlns="http://geofon.gfz-potsdam.de/ns/seiscomp3-schema/0.11" version="0.11">
<EventParameters publicID="smi:test/EventParameters">
<origin publicID="smi:test/origin">
<time>
<value>2018-12-12T00:00:00.000000Z</value>
<pdf>
<variable>2018-12-12T00:00:00 2018-12-12T00:00:00 2018-12-12T00:00:00</variable>
<probability>0.4 1.1 1.3</probability>
</pdf>
</time>
<latitude>
<value>20</value>
</latitude>
<longitude>
<value>100</value> …
```

Use custom namespace to keep non-QuakeML nodes

---

src/trunk/libs/seiscomp3/core/strings.cpp

vsnprintf returns the number of characters printed EXCLUDING the null byte

BUG: Seiscomp::Core::stringify truncates the resulting string

---

src/trunk/apps/fdsnws/fdsnws/dataselect.py

The SC3 datamodel includes a restricted attribute at network, station and channel level.
A FDSNWS station query with ```restricted=false``` will exclude all streams with a restricted flag set to ```true``` either on the network, station or channel level.
In contrast, the FDSWS dataselect service currently evaluates the restricted flag only on the channel level. Restricted channels are only available after authentication using the queryauth URL. However, streams with restricted network but non restricted channel are public available.
This pull request changes the dataselect service to require authentication if a stream is restricted either on the network, station or channel level. Also the iteration is stopped early at network or station level if the restricted flag is found but no …

[trunk] fix dataselect restricted handling

---

src/trunk/libs/seiscomp3/datamodel/utils.h

Before the correction, the column Stat in the event tab was set to A in the case the evaluation status was not defined and that evaluation mode was equal to "manual".
I corrected the bug to replace A by M.

fix evaluation status

---

src/trunk/apps/fdsnws/fdsnws/event.py

There is a small error in this error message at `event.py`:
```
db = DatabaseInterface.Open(Application.Instance().databaseURI())
if db is None:
msg = "could not connect to database: %s" % dbq.errorMsg()
return self.renderErrorPage(req, http.SERVICE_UNAVAILABLE, msg, ro)
dbq = DataModel.DatabaseQuery(db)
```
which causes an `UnboundLocalError: local variable 'dbq' referenced before assignment` exception.

[fdsnws] Fix error message in event.py

---

src/trunk/apps/processing/scmag/magtool.cpp

If the median has been used to compute a network magnitude then reprocessing with `--keep-weights` produced the wrong result. This PR resolves the issue. It has been reported and tested by SED.

Fixes static magnitude reprocessing in combination with median

---

src/nettab/libs/python/nettab/basesc3.py
src/nettab/libs/python/nettab/convertUtils.py
src/nettab/libs/python/nettab/lineType.py
src/nettab/libs/python/nettab/nodesi.py
src/nettab/libs/python/nettab/nodesnslc.py
src/nettab/libs/python/nettab/tab.py

We are getting following error when we try to run seiscomp3 with python-2.7.5
```
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
```
```
print("Network: %s" % line, file=sys.stderr)
^
SyntaxError: invalid syntax
```

Manage backward compatibility with Python2.7

---

doc/build-doc.py

Correct bug at compilation when  SC_DOC GENERATE = ON
Note : using sphinx-2.4.2 many warnings when building doc  from *.rst files.
_Framework : (Centos8, Qt5, Postgresql, python3.6)_
Backward compatibility tested with python2.7

[python] doc/build_doc.py python3 support

---

src/trunk/apps/fdsnws/fdsnws/availability.py
src/trunk/apps/fdsnws/fdsnws/dataselect.py
src/trunk/apps/fdsnws/fdsnws/event.py
src/trunk/apps/fdsnws/fdsnws/request.py
src/trunk/apps/fdsnws/fdsnws/station.py

Hi,
this PR fixes the issue that unknown query filter parameters of HTTP GET requests were silently omitted. Instead, HTTP status code 400 should be returned (in accordance with the [FDSN webservice specs](https://www.fdsn.org/webservices/)).
```bash
$  curl -v -o - "http://localhost:8080/fdsnws/station/1/query?net=NET&foo=bar&foobar=foobar"
* About to connect() to localhost port 8080 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /fdsnws/station/1/query?net=NET&foo=bar&foobar=foobar HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Length: 240
< Access-Control-Expose-Headers: WWW-Authenticate
< Server: SeisComP3-FDSNWS/1.2.4
< Date: Sun, 07 Jun 2020 …
```

[fdsnws] Strictly parse HTTP GET requests

---

src/ipgp/apps/ew2sc3/ew2sc3.cpp

This modification catches cases when the incoming hyp2000arc message have blank magnitudes in the summary line.
In this case, no magnitudes are attached to the origin sent to SeisComP3.
In previous behaviour, magnitude at 0.0 were attached to the origin.
Magnitude being a log scale, a value of 0.0 has a meaning.

Better handling of incoming messages without magnitude

---

src/ipgp/apps/ew2sc3/ew2sc3.cpp

Several values were not correctly parsed because Fortran spaces and blank were not converted in zeroes in the strings.

Correct several blank/zero values parsing
